version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "9001:9001"
    volumes:
      - ./app:/app

  golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app

